# Example: Dev Overlay (patches base for dev environment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-service
          image: myrepo/my-service:dev
