# Example: Staging Overlay (patches base for staging environment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-service
          image: myrepo/my-service:staging
