version: "3.8"
services:
  nodejs-app:
    image: node:20
    working_dir: /app
    volumes:
      - ./your-nodejs-app:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
