version: "3.8"
services:
  pubsub:
    image: google/cloud-sdk:latest
    command:
      [
        "gcloud",
        "beta",
        "emulators",
        "pubsub",
        "start",
        "--host-port=0.0.0.0:8085",
      ]
    ports:
      - "8085:8085"
    environment:
      - PUBSUB_PROJECT_ID=dev-project
    restart: unless-stopped
