# Example: FluxCD Kustomization manifest
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-service
spec:
  interval: 10m0s
  path: ./devops/k8s/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system
  targetNamespace: default
